import { lazyPage, lazyNamedPage } from './lazyPage';

export const PublicPDFTools = lazyPage(() => import('../pages/PublicPDFTools/PublicPDFTools'));
export const PublicWizard = lazyPage(() => import('../pages/PublicFlow/PublicWizard'));
export const PDFToolsMergePDFPage = lazyPage(() => import('../pages/PDFTools/MergePDFPage'));
export const PDFToolsSplitPDFPage = lazyPage(() => import('../pages/PDFTools/SplitPDFPage'));
export const PDFToolsExtractPDFPage = lazyPage(() => import('../pages/PDFTools/ExtractPDFPage'));
export const PDFToolsDeletePDFPage = lazyPage(() => import('../pages/PDFTools/DeletePDFPage'));
export const PDFToolsReorderPDFPage = lazyPage(() => import('../pages/PDFTools/ReorderPDFPage'));
export const PDFToolsRotatePDFPage = lazyPage(() => import('../pages/PDFTools/RotatePDFPage'));
export const PDFToolsCropPDFPage = lazyPage(() => import('../pages/PDFTools/CropPDFPage'));
export const PDFToolsInsertPDFPage = lazyPage(() => import('../pages/PDFTools/InsertPDFPage'));
export const PDFToolsAddPageNumbersPage = lazyPage(() => import('../pages/PDFTools/AddPageNumbersPage'));
export const PDFToolsAddHeaderFooterPage = lazyPage(() => import('../pages/PDFTools/AddHeaderFooterPage'));
export const PDFToolsAddPasswordPage = lazyPage(() => import('../pages/PDFTools/AddPasswordPage'));
export const PDFToolsRemovePasswordPage = lazyPage(() => import('../pages/PDFTools/RemovePasswordPage'));
export const PDFToolsDigitalSignaturePage = lazyPage(() => import('../pages/PDFTools/DigitalSignaturePage'));
export const PDFToolsSetPermissionsPage = lazyPage(() => import('../pages/PDFTools/SetPermissions'));
export const PDFToolsRemoveMetadataPage = lazyPage(() => import('../pages/PDFTools/RemoveMetadataPage'));
export const PDFToolsEditMetadataPage = lazyPage(() => import('../pages/PDFTools/EditMetadataPage'));
export const SmartConversion = lazyPage(() => import('../components/PDFService/SmartConversion'));
export const PDFToolsSpellCheckPage = lazyPage(() => import('../pages/PDFTools/SpellCheckPage'));
export const PDFToolsFindReplacePage = lazyPage(() => import('../pages/PDFTools/FindReplacePage'));
export const PDFToolsRedactContentPage = lazyPage(() => import('../pages/PDFTools/RedactContentPage'));
export const PDFToolsAddStampsPage = lazyPage(() => import('../pages/PDFTools/AddStampsPage'));
export const PDFToolsDBAddCommentsPage = lazyPage(() => import('../pages/PDFTools/DBAddCommentsPage'));
export const PDFToolsSharedDocumentPage = lazyPage(() => import('../pages/PDFTools/SharedDocumentPage'));
export const PDFToolsCompressPDFPage = lazyPage(() => import('../pages/PDFTools/CompressPDFPage'));
export const PDFToolsOptimizeImagePage = lazyPage(() => import('../pages/PDFTools/OptimizeImagePage'));
export const PDFToolsOptimizeFontPage = lazyPage(() => import('../pages/PDFTools/OptimizeFontPage'));
export const PDFToolsRemoveUnusedObjectsPage = lazyPage(() => import('../pages/PDFTools/RemoveUnusedObjectsPage'));
export const PDFToolsLinearizePDFPage = lazyPage(() => import('../pages/PDFTools/LinearizePDFPage'));
export const PDFToolsColorOptimizationPage = lazyPage(() => import('../pages/PDFTools/ColorOptimizationPage'));
export const PDFToolsQualityAnalysisPage = lazyPage(() => import('../pages/PDFTools/QualityAnalysisPage'));
export const PDFToolsDocumentTrackingPage = lazyPage(() => import('../pages/PDFTools/DocumentTrackingPage'));
export const PDFToolsBatchOptimizationPage = lazyPage(() => import('../pages/PDFTools/BatchOptimizationPage'));
export const PDFToolsOCRPage = lazyPage(() => import('../pages/PDFTools/OCRPage'));
export const PDFToolsMakeSearchablePage = lazyPage(() => import('../pages/PDFTools/MakeSearchablePage'));
export const PDFToolsExtractTablesPage = lazyPage(() => import('../pages/PDFTools/ExtractTablesPage'));
export const HandwritingRecognition = lazyPage(() => import('../pages/PDFTools/HandwritingRecognitionPage'));
export const FillPdfFormPage = lazyPage(() => import('../pages/PDFTools/FillPdfFormPage'));
export const FormRecognitionPage = lazyPage(() => import('../pages/PDFTools/FormRecognitionPage'));
export const CalculateFieldsPage = lazyPage(() => import('../pages/PDFTools/CalculateFieldsPage'));
export const PdfInfoPage = lazyPage(() => import('../pages/PDFTools/PdfInfoPage'));
export const PdfValidatorPage = lazyPage(() => import('../pages/PDFTools/PdfValidatorPage'));
export const PdfComparePage = lazyPage(() => import('../pages/PDFTools/PdfComparePage'));
export const PdfRepairPage = lazyPage(() => import('../pages/PDFTools/PdfRepairPage'));
export const PdfBookmarksPage = lazyPage(() => import('../pages/PDFTools/PdfBookmarksPage'));
export const PdfStatisticsPage = lazyPage(() => import('../pages/PDFTools/PdfStatisticsPage'));
export const SharedDocumentPage = lazyPage(() => import('../pages/DocumentService/SharedDocumentPage'));
export const SharedDocument = lazyPage(() => import('../pages/SharedDocument'));
export const StatusPage = lazyPage(() => import('../pages/LandingPage/StatusPage'));
export const ContactSales = lazyPage(() => import('../pages/LandingPage/ContactSales'));
export const BlogPage = lazyPage(() => import('../pages/LandingPage/BlogPage'));
export const AboutPage = lazyPage(() => import('../pages/LandingPage/AboutPage'));
export const WhyDocuSignerPage = lazyPage(() => import('../pages/LandingPage/WhyDocuSignerPage'));
export const LoginPage = lazyPage(() => import('../pages/LandingPage/LoginPage'));
export const SignupPage = lazyPage(() => import('../pages/LandingPage/SignupPage'));
export const FederatedOAuthCallbackPage = lazyPage(() => import('../pages/LandingPage/FederatedOAuthCallbackPage'));
export const ForgotPasswordPage = lazyPage(() => import('../pages/LandingPage/ForgotPasswordPage'));
export const ResetPasswordPage = lazyPage(() => import('../pages/LandingPage/ResetPasswordPage'));
export const PrivacyPolicyPage = lazyPage(() => import('../pages/LandingPage/PrivacyPolicyPage'));
export const CookiePolicyPage = lazyPage(() => import('../pages/LandingPage/CookiePolicyPage'));
export const TermsOfServicePage = lazyPage(() => import('../pages/LandingPage/TermsOfServicePage'));
export const UseCasesPage = lazyPage(() => import('../pages/LandingPage/UseCasesPage'));
export const WorkspacePage = lazyPage(() => import('../pages/LandingPage/WorkspacePage'));
export const FeatureComparisonPage = lazyPage(() => import('../pages/LandingPage/FeatureComparisonPage'));
export const SitemapPage = lazyPage(() => import('../pages/LandingPage/SitemapPage'));
export const ChoosePlanPage = lazyPage(() => import('../pages/LandingPage/ChoosePlanPage'));
export const NotFoundPage = lazyPage(() => import('../pages/LandingPage/NotFoundPage'));
export const DashboardPage = lazyPage(() => import('../pages/Dashboard/DashboardPage'));
export const AuditTrailPage = lazyPage(() => import('../pages/Dashboard/AuditTrailPage'));
export const CreditsUsagePage = lazyPage(() => import('../pages/Dashboard/CreditsUsagePage'));
export const CompliancePage = lazyPage(() => import('../pages/Dashboard/CompliancePage'));
export const RiskManagementPage = lazyPage(() => import('../pages/Dashboard/RiskManagementPage'));
export const SharedPDFPage = lazyPage(() => import('../pages/DocumentService/SharedPDFPage'));
export const FoldersPage = lazyPage(() => import('../pages/DocumentService/FoldersPage'));
export const RecentPage = lazyPage(() => import('../pages/DocumentService/RecentPage'));
export const FavoritesPage = lazyPage(() => import('../pages/DocumentService/FavoritesPage'));
export const ArchivedPage = lazyPage(() => import('../pages/DocumentService/ArchivedPage'));
export const TrashPage = lazyPage(() => import('../pages/DocumentService/TrashPage'));
export const EsignDashboard = lazyPage(() => import('../pages/eSign/Dashboard'));
export const EsignSigningPage = lazyPage(() => import('../pages/eSign/SigningPage'));
export const EsignAnalytics = lazyPage(() => import('../pages/eSign/Analytics'));
export const EsignSettings = lazyPage(() => import('../pages/eSign/Settings'));
export const EsignEnterpriseSettings = lazyPage(() => import('../pages/eSign/EnterpriseSettings'));
export const EsignESignatureAdmin = lazyPage(() => import('../pages/eSign/ESignatureAdmin'));
export const VSignAdminSettings = lazyPage(() => import('../pages/eSign/VSignAdminSettings'));
export const AdminLocalLogin = lazyPage(() => import('../pages/eSign/AdminLocalLogin'));
export const AITemplateGenerator = lazyPage(() => import('../pages/Template/AITemplateGenerator'));
export const UserProfile = lazyPage(() => import('../pages/Account/UserProfile'));
export const RewardsPage = lazyPage(() => import('../pages/Account/RewardsPage'));
export const SessionManagementPage = lazyPage(() => import('../pages/Account/SessionManagementPage'));
export const AuthMethodsPage = lazyPage(() => import('../pages/Account/AuthMethodsPage'));
export const AddWatermark = lazyPage(() => import('../components/PDFService/AddWatermark'));
export const ApiServiceDashboard = lazyPage(() => import('../pages/ApiService/Dashboard/main'));
export const ApiServiceAnalytics = lazyPage(() => import('../pages/ApiService/Analytics/Main'));
export const ApiServiceProjects = lazyPage(() => import('../pages/ApiService/Projects/Main'));
export const ApiServiceKey = lazyPage(() => import('../pages/ApiService/Key/Main'));
export const ApiServiceIntegrationDemo = lazyPage(() => import('../pages/ApiService/Demo/IntegrationDemo'));
export const ApiServiceExplorer = lazyPage(() => import('../pages/ApiService/Explorer/ApiExplorer'));
export const ApiServiceDocumentation = lazyPage(() => import('../pages/ApiService/Documentation/Main'));
export const ApiServiceWebhooks = lazyPage(() => import('../pages/ApiService/Webhooks/Main'));
export const ApiServiceSDK = lazyPage(() => import('../pages/ApiService/Sdk/main'));
export const ApiServiceTesting = lazyPage(() => import('../pages/ApiService/Testing/Main'));
export const ApiServiceMarketPlace = lazyPage(() => import('../pages/ApiService/MarketPlace/Main'));
export const ApiServiceCommunity = lazyPage(() => import('../pages/ApiService/Community/Main'));
export const ApiServiceSupport = lazyPage(() => import('../pages/ApiService/Support/Main'));
export const PublicSignerPage = lazyPage(() => import('../pages/eSign/PublicSignerPage'));
export const RecipientPortalPage = lazyPage(() => import('../pages/eSign/RecipientPortalPage'));
export const CreatePdfFormPage = lazyPage(() => import('../pages/PDFTools/CreatePdfFormPage'));
export const OAuthCallback = lazyPage(() => import('../pages/OAuthCallback'));
export const AdvancedPDFEditor = lazyPage(() => import('../components/PDFService/AdvancedPDFEditor'));
export const SecurityOverviewPage = lazyPage(() => import('../pages/LandingPage/SecurityOverviewPage'));
export const ESignServiceWebAppPage = lazyPage(() => import('../pages/LandingPage/InsidePages/ESignServiceWebAppPage'));
export const AIPoweredFeaturesPage = lazyPage(() => import('../pages/LandingPage/AIPoweredFeaturesPage'));
export const EnvelopeDetailPage = lazyPage(() => import('../pages/eSign/EnvelopeDetailPage'));
export const EnvelopeCreator = lazyPage(() => import('../pages/eSign/EnvelopeCreator'));
export const AgreementPage = lazyPage(() => import('../pages/eSign/AgreementPage'));
export const EnvelopeTypes = lazyPage(() => import('../pages/eSign/EnvelopeTypes'));
export const ManageRecipients = lazyPage(() => import('../pages/eSign/ManageRecipients'));
export const EnvelopeGuideSupport = lazyPage(() => import('../pages/eSign/EnvelopeGuideSupport'));
export const HelpSupportPage = lazyPage(() => import('../pages/LandingPage/HelpSupportPage'));
export const PowerFormCreate = lazyPage(() => import('../pages/eSign/PowerFormCreate'));
export const SubscriptionManagementPage = lazyPage(() => import('../pages/Account/SubscriptionManagementPage'));
export const InvoicePage = lazyPage(() => import('../pages/Account/InvoicePage'));
export const ThankYouPage = lazyPage(() => import('../pages/eSign/ThankYou'));
export const SignerStatusPage = lazyPage(() => import('../pages/eSign/SignerStatusPage'));
export const FinishLaterPage = lazyPage(() => import('../pages/eSign/FinishLaterPage'));
export const NotificationsPage = lazyPage(() => import('../pages/Notifications/NotificationsPage'));
export const SignerCycle = lazyPage(() => import('../pages/eSign/SignerCycle'));
export const CreateOrganizationPage = lazyPage(() => import('../pages/Organization/CreateOrganizationPage'));
export const MyOrganizationPage = lazyPage(() => import('../pages/Organization/MyOrganizationPage'));
export const OrganizationFolder = lazyPage(() => import('../pages/Organization/organizationFolder'));
export const BookDemoPage = lazyPage(() => import('../pages/LandingPage/BookDemoPage'));
export const EmailPage = lazyPage(() => import('../pages/EmailService/EmailPage'));
export const EmailTemplatesBuilder = lazyPage(() => import('../pages/EmailService/EmailTemplatesBuilder'));
export const InvitationPage = lazyPage(() => import('../pages/Organization/invitaionPage'));
export const FolderDetailPage = lazyPage(() => import('../pages/Organization/folderDetailPage'));
export const RolePage = lazyPage(() => import('../pages/Organization/RolePage'));
export const CouponPage = lazyPage(() => import('../pages/Account/CouponPage'));
export const SharedDocumentsPage = lazyNamedPage(() => import('../pages/DocumentService/SharedDocumentsPage'), 'SharedDocumentsPage');
export const PowerFormEmbed = lazyNamedPage(() => import('../pages/eSign/PowerFormEmbed'), 'PowerFormEmbed');
export const TemplateDashboard = lazyNamedPage(() => import('../pages/Template/Dashboard'), 'Dashboard');
export const TemplateDesigner = lazyNamedPage(() => import('../pages/Template/TemplateDesigner'), 'TemplateDesigner');
export const AdvancedTemplateDesigner = lazyNamedPage(() => import('../pages/Template/AdvancedTemplateDesigner'), 'AdvancedTemplateDesigner');
export const AITemplateStudio = lazyNamedPage(() => import('../pages/Template/AITemplateStudio'), 'AITemplateStudio');
export const TemplateLibrary = lazyNamedPage(() => import('../pages/Template/TemplateLibrary'), 'TemplateLibrary');
export const FormBuilder = lazyNamedPage(() => import('../pages/Template/FormBuilder'), 'FormBuilder');
export const TemplateMarketplace = lazyNamedPage(() => import('../pages/Template/TemplateMarketplace'), 'TemplateMarketplace');
export const TemplateAnylytics = lazyNamedPage(() => import('../pages/Template/Analytics'), 'Analytics');
export const APIManagement = lazyNamedPage(() => import('../pages/Template/APIManagement'), 'APIManagement');
export const WorkflowAutomation = lazyNamedPage(() => import('../pages/Template/WorkflowAutomation'), 'WorkflowAutomation');
export const TemplateAdminDashboard = lazyNamedPage(() => import('../pages/Template/TemplateAdminDashboard'), 'TemplateAdminDashboard');
export const FormsList = lazyNamedPage(() => import('../pages/Template/FormList'), 'FormsList');
export const FormView = lazyNamedPage(() => import('../pages/Template/FormView'), 'FormView');
export const FormEmbed = lazyNamedPage(() => import('../pages/Template/FormEmbed'), 'FormEmbed');
export const FormSubmissions = lazyNamedPage(() => import('../pages/Template/FormSubmissions'), 'FormSubmissions');
export const ToolsGrid = lazyNamedPage(() => import('../components/PDFService/ToolsGrid'), 'ToolsGrid');
export const HelpSystem = lazyNamedPage(() => import('../components/PDFService/HelpSystem'), 'HelpSystem');
export const CloudConnector = lazyNamedPage(() => import('../components/PDFService/CloudConnector'), 'CloudConnector');
export const WorkflowDesigner = lazyNamedPage(() => import('../components/PDFService/WorkflowDesigner'), 'WorkflowDesigner');
export const Analytics = lazyNamedPage(() => import('../components/PDFService/Analytics'), 'Analytics');
export const Header = lazyNamedPage(() => import('../components/PDFService/Header'), 'Header');
export const PdftoDoc = lazyNamedPage(() => import('../pages/PDFTools/PDFtoDoc'), 'PdftoDoc');
export const DoctoPdf = lazyNamedPage(() => import('../pages/PDFTools/DoctoPdf'), 'DoctoPdf');
export const PdfToExcel = lazyNamedPage(() => import('../pages/PDFTools/PdftoExcel'), 'PdfToExcel');
export const ExcelToPdf = lazyNamedPage(() => import('../pages/PDFTools/ExceltoPdf'), 'ExcelToPdf');
export const PdftoPpt = lazyNamedPage(() => import('../pages/PDFTools/PdftoPpt'), 'PdftoPpt');
export const PptToPdf = lazyNamedPage(() => import('../pages/PDFTools/PpttoPDF'), 'PptToPdf');
export const PdftoText = lazyNamedPage(() => import('../pages/PDFTools/PdftoText'), 'PdftoText');
export const TextToPdf = lazyNamedPage(() => import('../pages/PDFTools/TextToPDF'), 'TextToPdf');
export const PdfToHtml = lazyNamedPage(() => import('../pages/PDFTools/PdfToHtml'), 'PdfToHtml');
export const HtmlToPdf = lazyNamedPage(() => import('../pages/PDFTools/HtmltoPdf'), 'HtmlToPdf');
export const PdfToImage = lazyNamedPage(() => import('../pages/PDFTools/PdftoImage'), 'PdfToImage');
export const ImageToPDF = lazyNamedPage(() => import('../pages/PDFTools/ImageToPdf'), 'ImageToPDF');
export const PdfToEpub = lazyNamedPage(() => import('../pages/PDFTools/PdfToEpub'), 'PdfToEpub');
export const BatchConversion = lazyNamedPage(() => import('../pages/PDFTools/BatchConversion'), 'BatchConversion');
export const PdfEditorPage = lazyNamedPage(() => import('../pages/PDFTools/PdfEditor'), 'PdfEditorPage');
export const PowerForm = lazyNamedPage(() => import('../pages/eSign/PowerForm'), 'PowerForm');
export const AccessibilityPage = lazyNamedPage(() => import('../pages/LandingPage'), 'AccessibilityPage');
export const AIFeatures = lazyNamedPage(() => import('../pages/LandingPage'), 'AIFeatures');
export const AllInOnePlatformPage = lazyNamedPage(() => import('../pages/LandingPage'), 'AllInOnePlatformPage');
export const APIDocumentationPage = lazyNamedPage(() => import('../pages/LandingPage'), 'APIDocumentationPage');
export const BugBountyPage = lazyNamedPage(() => import('../pages/LandingPage'), 'BugBountyPage');
export const DataResidencyPage = lazyNamedPage(() => import('../pages/LandingPage'), 'DataResidencyPage');
export const DocuSignerVsAdobeSignPage = lazyNamedPage(() => import('../pages/LandingPage'), 'DocuSignerVsAdobeSignPage');
export const DocuSignerVsDocuSignPage = lazyNamedPage(() => import('../pages/LandingPage'), 'DocuSignerVsDocuSignPage');
export const DocuSignerVsHelloSignPage = lazyNamedPage(() => import('../pages/LandingPage'), 'DocuSignerVsHelloSignPage');
export const DocuSignerVsPandaDocPage = lazyNamedPage(() => import('../pages/LandingPage'), 'DocuSignerVsPandaDocPage');
export const UploadDocumentPage = lazyNamedPage(() => import('../pages/LandingPage'), 'UploadDocumentPage');
export const SignerPage = lazyNamedPage(() => import('../pages/LandingPage'), 'SignerPage');
