// Landing Page Components
export { default as Header } from '../../components/LandingPage/Header';
export { default as Hero } from '../../components/LandingPage/Hero';
export { default as ModernDocumentFeatures } from '../../components/LandingPage/ModernDocumentFeatures';
export { default as ComprehensivePlatform } from '../../components/LandingPage/ComprehensivePlatform';
export { default as PDFTools } from '../../components/LandingPage/PDFTools';
export { default as ESignature } from '../../components/LandingPage/ESignature';
export { default as LegalTemplates } from '../../components/LandingPage/LegalTemplates';
export { default as APISection } from '../../components/LandingPage/APISection';
export { default as Compliance } from '../../components/LandingPage/Compliance';
export { default as Pricing } from '../../components/LandingPage/Pricing';
export { default as FeatureComparison } from '../../components/LandingPage/FeatureComparison';
export { default as AIFeatures } from '../../components/LandingPage/AIFeatures';
export { default as Testimonials } from '../../components/LandingPage/Testimonials';
export { default as FAQ } from '../../components/LandingPage/FAQ';
export { default as CTASection } from '../../components/LandingPage/CTASection';
export { default as Footer } from '../../components/LandingPage/Footer';

// Landing Page Pages
export { default as DigitalSignaturePage } from './DigitalSignaturePage';
export { default as CompareDocumentsPage } from './CompareDocumentsPage';
export { default as BookletCreatorPage } from './BookletCreatorPage';
export { default as TableOfContentsPage } from './TableOfContentsPage';
export { default as AlternateAndMixPage } from './AlternateAndMixPage';
export { default as AllInOnePlatformPage } from './AllInOnePlatformPage';
export { default as APIDocumentationPage } from './APIDocumentationPage';
export { default as BugBountyPage } from './BugBountyPage';
export { default as DataResidencyPage } from './DataResidencyPage';
export { default as DocuSignerVsAdobeSignPage } from './DocuSignerVsAdobeSignPage';
export { default as DocuSignerVsDocuSignPage } from './DocuSignerVsDocuSignPage';
export { default as DocuSignerVsHelloSignPage } from './DocuSignerVsHelloSignPage';
export { default as DocuSignerVsPandaDocPage } from './DocuSignerVsPandaDocPage';
// export { default as HowItWorksPage } from './HowItWorks';
// export { default as SecurityOverviewPage } from './SecurityOverview';
export { default as StatusPage } from './StatusPage';
export { default as WhyDocuSignerPage } from './WhyDocuSignerPage';
export { default as AccessibilityPage } from './AccessibilityPage';
export { default as LoginPage } from './LoginPage';
export { default as SignupPage } from './SignupPage';
export { default as ForgotPasswordPage } from './ForgotPasswordPage';
export { default as ResetPasswordPage } from './ResetPasswordPage';
export { default as PrivacyPolicyPage } from './PrivacyPolicyPage';
export { default as TermsOfServicePage } from './TermsOfServicePage';
export { default as ESignServiceWebAppPage } from './InsidePages/ESignServiceWebAppPage';
export { default as UploadDocumentPage } from './UploadDocumentPage';
export { default as SignerPage } from './SignerPage';
export { default as ChoosePlanPage } from './ChoosePlanPage';
