const express = require('express');
const { login, register } = require('../controllers/authController');
const {adminLogin} = require('../controllers/adminAuthController');
const { userDetails } = require('../controllers/mainController');
const verifyJWT  = require('@draftnsign/auth-lib');
const router = express.Router();
router.get('/status', (_, res) => res.send('Auth Service is running and changing'));
router.post('/login', login);
router.post('/admin/login', adminLogin);
router.post('/register', register);
router.get('/api/user-details/:id', userDetails);
module.exports = router;
