const Ticket = require('../models/Ticket');
const Message = require('../models/Message');
const Customer = require('../models/Customer');
const SupportAgent = require('../models/SupportAgent');
const { routeTicketToAgent, removeTicketFromAgent } = require('../utils/ticketRouter');

// Create a new ticket
exports.createTicket = async (req, res) => {
  try {
    const { subject, category, priority, initialMessage, metadata } = req.body;
    const customerId = req.user.data.id;

    if (!subject || !initialMessage) {
      return res.status(400).json({
        status: 400,
        message: 'Subject and initial message are required',
        data: null
      });
    }

    // Create or update customer record
    let customer = await Customer.findOne({ userId: customerId });
    if (!customer) {
      // Get user details from User model (assuming it exists in auth-service)
      customer = new Customer({
        userId: customerId,
        email: req.user.data.email || '',
        fullname: req.user.data.fullname || '',
        phone: req.user.data.phone || null
      });
      await customer.save();
    }

    // Create ticket (ticketNumber will be auto-generated by pre-validate hook)
    const ticket = new Ticket({
      customerId: customerId,
      subject,
      category: category || 'other',
      priority: priority || 'medium',
      status: 'open',
      metadata: metadata || {}
    });
    
    // Ensure ticketNumber is generated before saving
    if (!ticket.ticketNumber) {
      const timestamp = Date.now();
      const random = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
      ticket.ticketNumber = `TKT-${timestamp}-${random}`;
    }
    
    await ticket.save();

    // Create initial message
    const message = new Message({
      ticketId: ticket._id,
      senderId: customerId,
      senderType: 'customer',
      content: initialMessage,
      messageType: 'text'
    });
    await message.save();

    // Update ticket last message time
    ticket.lastMessageAt = new Date();
    await ticket.save();

    // Update customer stats
    customer.totalTickets += 1;
    customer.activeTickets += 1;
    await customer.save();

    // Route ticket to available agent (async, won't block response)
    routeTicketToAgent(ticket._id).catch(err => {
      console.error('Error routing ticket:', err);
    });

    return res.status(201).json({
      status: 201,
      message: 'Ticket created successfully',
      data: {
        ticket,
        message
      }
    });
  } catch (error) {
    console.error('Create ticket error:', error);
    
    // Provide more specific error messages
    if (error.name === 'ValidationError') {
      const errors = Object.values(error.errors).map((e) => e.message).join(', ');
      return res.status(400).json({
        status: 400,
        message: `Validation error: ${errors}`,
        data: null
      });
    }
    
    if (error.code === 11000) {
      return res.status(400).json({
        status: 400,
        message: 'Duplicate ticket number. Please try again.',
        data: null
      });
    }
    
    return res.status(500).json({
      status: 500,
      message: error.message || 'Server error',
      data: null
    });
  }
};

// Get customer's tickets
exports.getCustomerTickets = async (req, res) => {
  try {
    const customerId = req.user.data.id;

    const tickets = await Ticket.find({ customerId })
      .populate('assignedAgentId', 'fullname email avatar status')
      .sort({ createdAt: -1 });

    return res.status(200).json({
      status: 200,
      message: 'Tickets retrieved successfully',
      data: { tickets }
    });
  } catch (error) {
    console.error('Get customer tickets error:', error);
    return res.status(500).json({
      status: 500,
      message: 'Server error',
      data: null
    });
  }
};

// Get single ticket details
exports.getTicket = async (req, res) => {
  try {
    const { ticketId } = req.params;
    const customerId = req.user.data.id;

    const ticket = await Ticket.findOne({
      _id: ticketId,
      customerId: customerId
    })
      .populate('assignedAgentId', 'fullname email avatar status');

    if (!ticket) {
      return res.status(404).json({
        status: 404,
        message: 'Ticket not found',
        data: null
      });
    }

    // Manually populate customer data
    const ticketObj = ticket.toObject();
    if (ticket.customerId) {
      const customer = await Customer.findOne({ userId: ticket.customerId });
      if (customer) {
        ticketObj.customerId = {
          _id: customer._id,
          email: customer.email,
          fullname: customer.fullname,
          phone: customer.phone
        };
      }
    }

    // Get messages for this ticket
    const messages = await Message.find({ ticketId })
      .sort({ createdAt: 1 });

    return res.status(200).json({
      status: 200,
      message: 'Ticket retrieved successfully',
      data: {
        ticket: ticketObj,
        messages
      }
    });
  } catch (error) {
    console.error('Get ticket error:', error);
    return res.status(500).json({
      status: 500,
      message: 'Server error',
      data: null
    });
  }
};

// Close ticket (customer)
exports.closeTicket = async (req, res) => {
  try {
    const { ticketId } = req.params;
    const customerId = req.user.data.id;

    const ticket = await Ticket.findOne({
      _id: ticketId,
      customerId: customerId
    });

    if (!ticket) {
      return res.status(404).json({
        status: 404,
        message: 'Ticket not found',
        data: null
      });
    }

    if (ticket.status === 'closed') {
      return res.status(400).json({
        status: 400,
        message: 'Ticket is already closed',
        data: null
      });
    }

    ticket.status = 'closed';
    ticket.closedAt = new Date();
    ticket.updatedAt = new Date();
    await ticket.save();

    // Update customer active tickets count
    const customer = await Customer.findOne({ userId: customerId });
    if (customer && customer.activeTickets > 0) {
      customer.activeTickets -= 1;
      await customer.save();
    }

    // Remove from agent's current tickets
    if (ticket.assignedAgentId) {
      await removeTicketFromAgent(ticket.assignedAgentId, ticket._id);
    }

    // Emit ticket_updated event to notify all connected clients
    const io = req.app.get('io');
    if (io) {
      io.to(`ticket_${ticketId}`).emit('ticket_updated', {
        ticketId: ticket._id.toString(),
        status: ticket.status,
        closedAt: ticket.closedAt
      });
    }

    return res.status(200).json({
      status: 200,
      message: 'Ticket closed successfully',
      data: { ticket }
    });
  } catch (error) {
    console.error('Close ticket error:', error);
    return res.status(500).json({
      status: 500,
      message: 'Server error',
      data: null
    });
  }
};

// Submit rating and feedback
exports.submitRating = async (req, res) => {
  try {
    const { ticketId } = req.params;
    const { score, feedback } = req.body;
    const customerId = req.user.data.id;

    if (!score || score < 1 || score > 5) {
      return res.status(400).json({
        status: 400,
        message: 'Rating score must be between 1 and 5',
        data: null
      });
    }

    const ticket = await Ticket.findOne({
      _id: ticketId,
      customerId: customerId,
      status: 'closed'
    });

    if (!ticket) {
      return res.status(404).json({
        status: 404,
        message: 'Closed ticket not found',
        data: null
      });
    }

    if (ticket.rating.score) {
      return res.status(400).json({
        status: 400,
        message: 'Ticket already rated',
        data: null
      });
    }

    ticket.rating = {
      score,
      feedback: feedback || null,
      ratedAt: new Date()
    };
    await ticket.save();

    // Update agent stats if ticket was assigned
    if (ticket.assignedAgentId) {
      const agent = await SupportAgent.findById(ticket.assignedAgentId);
      if (agent) {
        await agent.updateStats(null, score);
      }
    }

    return res.status(200).json({
      status: 200,
      message: 'Rating submitted successfully',
      data: { rating: ticket.rating }
    });
  } catch (error) {
    console.error('Submit rating error:', error);
    return res.status(500).json({
      status: 500,
      message: 'Server error',
      data: null
    });
  }
};

// Agent: Get assigned tickets
exports.getAssignedTickets = async (req, res) => {
  try {
    const agentEmail = req.agent.email;
    const { status } = req.query;

    // Find agent in support-service database by email (since IDs might differ)
    let agentId = req.agent.id;
    if (agentEmail) {
      const supportAgent = await SupportAgent.findOne({ email: agentEmail.toLowerCase() });
      if (supportAgent) {
        agentId = supportAgent._id;
      }
    }

    const query = { assignedAgentId: agentId };
    if (status) {
      query.status = status;
    }

    const tickets = await Ticket.find(query)
      .sort({ lastMessageAt: -1 });

    // Manually populate customer data from Customer model
    const ticketsWithCustomer = await Promise.all(tickets.map(async (ticket) => {
      const ticketObj = ticket.toObject();
      
      // Find customer by userId (which is stored in ticket.customerId)
      if (ticket.customerId) {
        const customer = await Customer.findOne({ userId: ticket.customerId });
        if (customer) {
          ticketObj.customerId = {
            _id: customer._id,
            email: customer.email,
            fullname: customer.fullname,
            phone: customer.phone
          };
        }
      }
      
      return ticketObj;
    }));

    return res.status(200).json({
      status: 200,
      message: 'Tickets retrieved successfully',
      data: { tickets: ticketsWithCustomer }
    });
  } catch (error) {
    console.error('Get assigned tickets error:', error);
    return res.status(500).json({
      status: 500,
      message: 'Server error',
      data: null
    });
  }
};

// Agent: Close ticket
exports.agentCloseTicket = async (req, res) => {
  try {
    const { ticketId } = req.params;
    const agentId = req.agent.id;

    const ticket = await Ticket.findOne({
      _id: ticketId,
      assignedAgentId: agentId
    });

    if (!ticket) {
      return res.status(404).json({
        status: 404,
        message: 'Ticket not found',
        data: null
      });
    }

    ticket.status = 'closed';
    ticket.closedAt = new Date();
    ticket.updatedAt = new Date();
    await ticket.save();

    // Update customer active tickets count
    const customer = await Customer.findOne({ userId: ticket.customerId });
    if (customer && customer.activeTickets > 0) {
      customer.activeTickets -= 1;
      await customer.save();
    }

    // Remove from agent's current tickets
    await removeTicketFromAgent(agentId, ticket._id);

    // Emit ticket_updated event to notify all connected clients
    const io = req.app.get('io');
    if (io) {
      io.to(`ticket_${ticketId}`).emit('ticket_updated', {
        ticketId: ticket._id.toString(),
        status: ticket.status,
        closedAt: ticket.closedAt
      });
    }

    return res.status(200).json({
      status: 200,
      message: 'Ticket closed successfully',
      data: { ticket }
    });
  } catch (error) {
    console.error('Agent close ticket error:', error);
    return res.status(500).json({
      status: 500,
      message: 'Server error',
      data: null
    });
  }
};

// Agent: Transfer ticket
exports.transferTicket = async (req, res) => {
  try {
    const { ticketId } = req.params;
    const { toAgentId, reason } = req.body;
    const fromAgentId = req.agent.id;

    if (!toAgentId) {
      return res.status(400).json({
        status: 400,
        message: 'Target agent ID is required',
        data: null
      });
    }

    const ticket = await Ticket.findOne({
      _id: ticketId,
      assignedAgentId: fromAgentId
    });

    if (!ticket) {
      return res.status(404).json({
        status: 404,
        message: 'Ticket not found',
        data: null
      });
    }

    const toAgent = await SupportAgent.findById(toAgentId);
    if (!toAgent || !toAgent.isActive) {
      return res.status(404).json({
        status: 404,
        message: 'Target agent not found or inactive',
        data: null
      });
    }

    // Record transfer in history
    ticket.transferHistory.push({
      fromAgentId,
      toAgentId,
      reason: reason || null,
      transferredAt: new Date()
    });

    // Update ticket assignment
    const fromAgent = await SupportAgent.findById(fromAgentId);
    if (fromAgent) {
      fromAgent.currentTickets = fromAgent.currentTickets.filter(
        t => t.ticketId.toString() !== ticketId.toString()
      );
      await fromAgent.save();
    }

    ticket.assignedAgentId = toAgentId;
    ticket.updatedAt = new Date();
    await ticket.save();

    // Add to new agent's current tickets
    toAgent.currentTickets.push({
      ticketId: ticket._id,
      assignedAt: new Date()
    });
    await toAgent.save();

    return res.status(200).json({
      status: 200,
      message: 'Ticket transferred successfully',
      data: { ticket }
    });
  } catch (error) {
    console.error('Transfer ticket error:', error);
    return res.status(500).json({
      status: 500,
      message: 'Server error',
      data: null
    });
  }
};

